### PR TITLE
cli: clarify start/end

### PR DESCRIPTION
**Pull request by nathanleiby**
Often, we run report-card within CI. We want to make sure that the logs
from report-card aren't confused with the repo's test failures.

To do this, I've added a header and footer (`REPORT-CARD <begin/end>`).
Note that it may be displayed in black and white in the CI output

The new output:

image

### CODE REVIEW

**Comment by nathanleiby** [comment]
cc: @meliaj @cozmo , who saw some confusion from this

**Comment by peggyl** [comment]
LGTM! :art: 

It looks like colors are supported in Drone output: https://ci.ops.clever.com/github.com/Clever/report-card/clarify-start-end/c3351e4ca30ca19e5a4dca50f117aa991811403c

**Comment by nathanleiby** [comment]
@peggyl ah, nice find! i think the issue was that bold text is having trouble. I've now updated bold things to be a color (cyan) instead ce774ab

**Comment by nathanleiby** [comment]
image

**Pull request merged**
