### PR TITLE
Adds security checks that look for unescaped output in templates

### PR DESCRIPTION
**Pull request by alsmola**
This branch adds a set of checks related to unescaped output in templates, which can lead to XSS issues. See [go/xss](https://docs.google.com/document/d/1U8T0OXxdXZiYPFFK2DpLVw49Y3EZDGtlt7dkeMduRhE/edit#heading=h.vlf69jnlygd2) for the source of the data about vulnerable calls. There are probably more XSS-related checks to add, but I want to get a sense of how well this approach works first.

The `security_checks.py` file is intended to contain other checks for security issues in the future, hence the name.

See [SEC-26](https://clever.atlassian.net/browse/SEC-26) for more context.

### CODE REVIEW

**Comment by nathanleiby** [comment]
Love it!

1. We need to enable report-card in more repos for this to be useful. I think report-card has now been running across ~10 repos long enough that I feel OK enabling it globally.

2. Normally, report-card doesn't ever *fail* a repo's Git Status. For security issues, we could consider whether report-card should return a fail. What do you think?

**Comment by nathanleiby** [comment]
FYI I don't think it's needed for this PR, but I have a ticket to think about supporting checks in report-card that are private (https://clever.atlassian.net/browse/INFRA-1540)

**Comment by alsmola** [comment]
1. Good to know. I think that's OK for now, but hopefully this would help encourage us to use it more widely.
2. I don't think we should fail for security-related checks. These issues could be false positives, and several repos would fail in their current state.

**Comment by nathanleiby** [comment]
1. Sounds good!
2. For the false positives, should users still update their code to follow
best-practices? (right now, report-card will still deduct a point if they
fail this check...)

**Comment by alsmola** [comment]
2. I think they should update their code. There's almost always a way to do things without including unescaped output. For now, I'm fine if this continues to be a "you should fix this" lint-type issue.

**Comment by alsmola** [comment]
@nathanleiby is there anything you'd like me to change? Or am I OK to merge this? There will be follow-up branches.

**Comment by nathanleiby** [comment]
Yes looks all good to me... Did you test running these checks locally?

**Comment by alsmola** [comment]
I did run them locally and verified they work.

**Comment by nathanleiby** [comment]
lgtm

**Pull request merged**
